### ISSUE TITLE
allowedHostPaths should set readOnly:true

### ISSUE THREAD

**Issue by liggitt** [sysdiglabs/kube-psp-advisor#11]
See https://kubernetes.io/docs/concepts/policy/pod-security-policy/#volumes-and-file-systems

> Warning:
> There are many ways a container with unrestricted access to the host filesystem can escalate privileges, including reading data from other containers, and abusing the credentials of system services, such as Kubelet.
> 
> Writeable hostPath directory volumes allow containers to write to the filesystem in ways that let them traverse the host filesystem outside the pathPrefix. readOnly: true, available in Kubernetes 1.11+, must be used on all allowedHostPaths to effectively limit access to the specified pathPrefix.

**Comment by Kaizhe** [comment]
Thanks for the comments @liggitt,  I will address that:)

**Comment by Kaizhe** [comment]
addressed in #12

**Comment by liggitt** [comment]
Thanks for the quick response. If the intent is to generate least privilege PSPs, I think you actually need to check if the volumeMounts are readonly. If so, readonly allowedHostPaths can be generated. If not, you can generate non-readonly allowedHostPaths, but it's probably worth emitting a warning that they will be ineffective at limiting the pods to that prefix

**Comment by Kaizhe** [comment]
You're right, thanks for pointing it out. Will fix it.

**Comment by Kaizhe** [comment]
Done.
