### ISSUE TITLE
make: *** No rule to make target 'build'.

### ISSUE THREAD

**Issue by ermusthofa** [sysdiglabs/kube-psp-advisor#21]
Hi,

I have followed the readme to build psp-advisor as a binary. But i still got same error
`make: *** No rule to make target 'build'.  Stop.`

any idea how to resolve this ?

Thank you

**Comment by Kaizhe** [comment]
@ermusthofa may I know the working directory where you run `make`?

**Comment by ermusthofa** [comment]
Hi @Kaizhe ,

I'm sorry for this trouble. I've managed to solve this, and all of the trouble comes from my mistake

I'm new to golang, and even didn't know how to build go project.


Once again, I'm sorry for this. And thank you for your response
