### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by erkolson** [sysdiglabs/kube-psp-advisor#28]
**Describe the bug**
Following the build instructions from README for both `make build` and building in a docker container, go build fails.

**To Reproduce**
1.  `docker build -t psp-advisor -f container/Dockerfile .`

**Expected behavior**
Build to complete successfully

**Desktop (please complete the following information):**
 - Mac OS 10.14.6

**Additional context**
```
Step 7/10 : RUN env GOOS=$(uname -s | tr '[:upper:]' '[:lower:]') GOARCH=amd64 CGO_ENABLED=0 go build -a
 ---> Running in 1d29495b81f6
# github.com/sysdiglabs/kube-psp-advisor/advisor/processor
advisor/processor/get.go:26:70: undefined: v1
advisor/processor/get.go:314:56: undefined: v1
advisor/processor/get.go:329:26: undefined: v1
advisor/processor/get.go:347:30: undefined: v1
advisor/processor/get.go:383:22: undefined: v1
advisor/processor/get.go:398:23: undefined: v1
advisor/processor/get.go:409:24: undefined: v1
advisor/processor/get.go:420:36: undefined: v1
advisor/processor/get.go:442:24: undefined: v1
advisor/processor/get.go:454:30: undefined: v1
advisor/processor/get.go:454:30: too many errors
The command '/bin/sh -c env GOOS=$(uname -s | tr '[:upper:]' '[:lower:]') GOARCH=amd64 CGO_ENABLED=0 go build -a' returned a non-zero code: 2
```

**Comment by Kaizhe** [comment]
@erkolson it works for me.  Are you using the latest commit? It looks like the `"k8s.io/api/core/v1"` is not loaded properly.

**Comment by erkolson** [comment]
Yes!  After the latest merge, I can now successfully build on master.  Thanks.
