### ISSUE TITLE
Please re-release since adding arm64 support

### ISSUE THREAD

**Issue by ghostsquad** [sysdiglabs/kube-psp-advisor#52]
ARM64 was added here:
https://github.com/sysdiglabs/kube-psp-advisor/commit/4114e4a042f4f93a0d3ea6a54a836ed3557e428b

but there hasn't been a release since then, thus it's still listed as unavailable in `krew search`.

**Comment by ghostsquad** [comment]
Workaround for now is

```shell
KREW_ARCH=amd64 kubectl krew install advise-psp
```

**Comment by Kaizhe** [comment]
@mstemm can someone from the open source team help here to create another release ?

**Comment by mstemm** [comment]
Yes, let me ask about that tomorrow.

**Comment by mstemm** [comment]
I created a tag v3.0.0 and a release from that tag, but it looks like the release process is more than making a github release. @Kaizhe can you explain how to make a release?

**Comment by Kaizhe** [comment]
Making a release should be good, then it's going to automatically trigger new build in the krew plugin.

**Comment by Kaizhe** [comment]
Hmm, why the binary is not generated ?

**Comment by mstemm** [comment]
How about we discuss in the kubernetes slack?

**Comment by mstemm** [comment]
@Kaizhe and I debugged, I also needed to update the go version for the github workflow to 1.16. I see the release now:

```$ kubectl krew info advise-psp
kubectl krew info advise-psp
NAME: advise-psp
INDEX: default
URI: https://github.com/sysdiglabs/kube-psp-advisor/releases/download/v3.0.1/kube-psp-advisor_v3.0.1_darwin_amd64.tar.gz
SHA256: 3752234c16cac7ad602f4462c0d47ed208b019ddc8a25fb13779bbd3ea9ab531
VERSION: v3.0.1
HOMEPAGE: https://github.com/sysdiglabs/kube-psp-advisor
DESCRIPTION:
Suggests PSPs based on the required capabilities of the currently running
workloads or a given manifest.
```
